package com.loan_manage.web_service.impl;

import com.loan_manage.web_service.OaViewPersonWebService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-02T17:33:19.424+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "OaViewPersonWebServiceImplService", 
                  wsdlLocation = "http://192.168.1.42:9091/OAOperationCenter/oaview?wsdl",
                  targetNamespace = "http://impl.webservice.oper.jinhuhang.com/") 
public class OaViewPersonWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.oper.jinhuhang.com/", "OaViewPersonWebServiceImplService");
    public final static QName OaViewPersonWebServiceImplPort = new QName("http://impl.webservice.oper.jinhuhang.com/", "OaViewPersonWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.42:9091/OAOperationCenter/oaview?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OaViewPersonWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.42:9091/OAOperationCenter/oaview?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OaViewPersonWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OaViewPersonWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OaViewPersonWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OaViewPersonWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OaViewPersonWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OaViewPersonWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OaViewPersonWebService
     */
    @WebEndpoint(name = "OaViewPersonWebServiceImplPort")
    public OaViewPersonWebService getOaViewPersonWebServiceImplPort() {
        return super.getPort(OaViewPersonWebServiceImplPort, OaViewPersonWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OaViewPersonWebService
     */
    @WebEndpoint(name = "OaViewPersonWebServiceImplPort")
    public OaViewPersonWebService getOaViewPersonWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(OaViewPersonWebServiceImplPort, OaViewPersonWebService.class, features);
    }

}
